import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { webcrypto } from 'node:crypto';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');
const app=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const clone=x=>structuredClone(x);
const validReading=(extra={})=>({id:'test-reading',date:'2024-01-10',time:'08:00',period:'AM',sys:120,dia:80,pulse:70,excluded:false,notes:'',recordedAt:'2024-01-10T08:00:00Z',...extra});

test('Dublin date rolls over correctly during summer time',()=>assert.equal(app.dateKey(new Date('2026-08-30T23:30:00Z')),'2026-08-31'));
test('Dublin winter date does not invent a summer offset',()=>assert.equal(app.dateKey(new Date('2026-01-01T23:30:00Z')),'2026-01-01'));
test('Calendar validates leap years and rejects overflowing dates',()=>{assert.equal(app.validDate('2024-02-29'),true);assert.equal(app.validDate('2025-02-29'),false);assert.equal(app.validDate('2026-13-01'),false);assert.equal(app.validDate('not a date'),false);});
test('Calendar day arithmetic survives the spring clock change',()=>{assert.equal(app.addDays('2026-03-28',2),'2026-03-30');assert.equal(app.daysBetween('2026-03-28','2026-03-30'),2);});
test('Calendar day arithmetic survives the autumn clock change',()=>assert.equal(app.daysBetween('2026-10-24','2026-10-26'),2));
test('No BP is represented as missing, never zero',()=>assert.deepEqual(app.averageBP([]),{sys:null,dia:null,pulse:null,count:0,days:0}));
test('Two BP readings average correctly',()=>assert.deepEqual(app.averageBP([validReading({sys:120,dia:80,pulse:72}),validReading({id:'two',sys:118,dia:78,pulse:68})]),{sys:119,dia:79,pulse:70,count:2,days:1}));
test('Excluded measurement errors do not affect an average',()=>assert.equal(app.averageBP([validReading(),validReading({id:'two',sys:200,dia:130,excluded:true})]).sys,120));
test('Missing pulse is not zero',()=>assert.equal(app.averageBP([validReading({pulse:null})]).pulse,null));
test('BP validation accepts very high readings so safety handling can act',()=>assert.deepEqual(app.validateBP(validReading({sys:190,dia:120})),[]));
test('BP validation rejects partial readings and inverted numbers',()=>{assert.ok(app.validateBP(validReading({sys:null})).length);assert.ok(app.validateBP(validReading({sys:80,dia:120})).length);});
test('BP validation rejects nonfinite, fractional and future readings',()=>{for(const r of [validReading({sys:Infinity}),validReading({dia:80.5}),validReading({date:app.addDays(app.dateKey(),1)})])assert.ok(app.validateBP(r).length);});
test('Systolic 180 alone triggers the high-pressure advice',()=>assert.equal(app.triage({}, {sys:180,dia:85}).level,'urgent'));
test('Diastolic 120 alone triggers the high-pressure advice',()=>assert.equal(app.triage({}, {sys:160,dia:120}).level,'urgent'));
test('Emergency neurological flags are independent of a normal BP',()=>{for(const flag of Object.keys(app.EMERGENCY))assert.equal(app.triage({[flag]:true},{sys:118,dia:75}).level,'emergency');});
test('Wound concerns prompt clinical advice rather than a recovery score',()=>assert.equal(app.triage({woundLeak:true}).level,'urgent'));
test('Emergency advice takes precedence over wound advice',()=>assert.equal(app.triage({speech:true,woundRed:true}).level,'emergency'));
test('No selected flags do not produce a safe/cleared classification',()=>assert.equal(app.triage({}).level,'none'));
test('Irish standard drinks use 10g, not UK units',()=>assert.ok(Math.abs(app.standardDrinks(500,5)-1.9725)<1e-8));
test('Wine calculation uses actual volume and ABV',()=>assert.ok(Math.abs(app.standardDrinks(150,12)-1.4202)<1e-8));
test('Invalid alcohol input is not coerced to a real quantity',()=>{assert.equal(app.standardDrinks(null,5),null);assert.equal(app.standardDrinks(500,101),null);assert.equal(app.standardDrinks(-2,5),null);});
test('Missing alcohol log stays unknown',()=>{assert.equal(app.alcoholTotal({}),null);assert.equal(app.alcoholTotal({alcoholNone:true}),0);});
test('Smoke-free streak counts only consecutive explicit zeros',()=>{const d={'2024-01-08':{cigarettes:0},'2024-01-09':{cigarettes:0},'2024-01-10':{cigarettes:0}};assert.equal(app.streak(d,'smoke','2024-01-10').count,3);delete d['2024-01-09'];assert.equal(app.streak(d,'smoke','2024-01-10').count,1);});
test('A smoking lapse ends a current zero-cigarette streak without deleting earlier logs',()=>{const d={'2024-01-09':{cigarettes:0},'2024-01-10':{cigarettes:1}};assert.equal(app.streak(d,'smoke','2024-01-10').count,0);assert.equal(d['2024-01-09'].cigarettes,0);});
test('Unlogged today can show a streak through yesterday, not claim today',()=>{const x=app.streak({'2024-01-09':{cigarettes:0}},'smoke','2024-01-10');assert.equal(x.count,1);assert.equal(x.through,'2024-01-09');assert.equal(x.today,false);});
test('Alcohol streak requires explicit no-alcohol entries',()=>assert.equal(app.streak({'2024-01-09':{alcoholNone:true},'2024-01-10':{alcoholNone:true}},'alcohol','2024-01-10').count,2));
test('CSV quotes text and neutralises spreadsheet formulas',()=>{assert.equal(app.csvCell('a,"b"'),'"a,""b"""');for(const value of ['=SUM(1,2)',' +123','-10','@x','\tformula'])assert.ok(app.csvCell(value).startsWith('"\''));});
test('Initial state contains no invented surgery date, targets or health readings',()=>{const s=app.initialState();assert.equal(s.profile.operationDate,'');assert.equal(s.profile.sysMax,null);assert.equal(s.profile.fluidTarget,null);assert.equal(s.profile.typicalSteps,null);assert.equal(s.profile.alcoholReviewed,false);assert.equal(s.bp.length,0);assert.equal(Object.keys(s.daily).length,0);assert.equal(app.validateState(s).schema,1);});
test('Backup validator rejects prototype-pollution keys',()=>{const s=app.initialState();s.extra=JSON.parse('{"__proto__":{"polluted":true}}');assert.throws(()=>app.validateState(s));assert.equal({}.polluted,undefined);});
test('Backup validator rejects excessive nesting',()=>{const s=app.initialState();let p=s;for(let i=0;i<22;i++){p.extra={};p=p.extra;}assert.throws(()=>app.validateState(s));});
test('Backup validator rejects out-of-range symptoms and invalid profile selections',()=>{const s=app.initialState();s.daily['2024-01-10']={headacheAM:80};assert.throws(()=>app.validateState(s));const x=app.initialState();x.profile.thermomix='unsafe-value';assert.throws(()=>app.validateState(x));});
test('Backup validator rejects duplicate BP identifiers',()=>{const s=app.initialState();s.bp=[validReading(),validReading()];assert.throws(()=>app.validateState(s));});
test('Backup validator rejects contradictory alcohol-zero claims',()=>{const s=app.initialState();s.daily['2024-01-10']={alcoholNone:true,drinks:[{id:'drink-1',name:'Synthetic drink',time:'18:00',ml:100,abv:5,notes:''}]};assert.throws(()=>app.validateState(s));});
test('Backup validator requires details for a claimed alcohol discussion',()=>{const s=app.initialState();s.profile.alcoholReviewed=true;assert.throws(()=>app.validateState(s));});
test('Backup validator allows future planning but not future meals marked eaten',()=>{const s=app.initialState();const d=app.addDays(app.dateKey(),2);s.mealPlan[d]={breakfast:{recipeId:'berry-oats',servings:1,eaten:false}};assert.equal(app.validateState(s).schema,1);s.mealPlan[d].breakfast.eaten=true;assert.throws(()=>app.validateState(s));});
test('There are 28 unique complete original recipes',()=>{assert.equal(app.RECIPES.length,28);assert.equal(new Set(app.RECIPES.map(r=>r.id)).size,28);for(const r of app.RECIPES){assert.ok(r.ingredients.length>=3);assert.ok(r.servings>0);assert.ok(r.tm.length>50);assert.ok(r.hob.length>20);assert.ok(r.note.length>15);assert.ok(Array.isArray(r.allergens));for(const i of r.ingredients){assert.ok(Number.isFinite(i.amount)&&i.amount>0);assert.ok(['g','mL'].includes(i.unit));}}});
test('All meal slots have useful choices',()=>{for(const slot of ['breakfast','lunch','dinner','snack'])assert.ok(app.RECIPES.filter(r=>r.slot===slot).length>=5);});
test('Shopping scales portions and combines identical ingredients',()=>{const plan={'2024-01-10':{breakfast:{recipeId:'berry-oats',servings:1,eaten:false}},'2024-01-11':{breakfast:{recipeId:'berry-oats',servings:2,eaten:false}}};const out=app.shopping(plan);assert.equal(out.find(i=>i.key==='oats').amount,180);assert.equal(out.find(i=>i.key==='milk').amount,600);assert.equal(out.filter(i=>i.key==='oats').length,1);});
test('Shopping does not add tap water to groceries or infer a meal from an empty slot',()=>{const out=app.shopping({'2024-01-10':{lunch:{recipeId:'lentil-soup',servings:1,eaten:false}}});assert.ok(!out.some(i=>i.key==='water'));assert.deepEqual(app.shopping({}),[]);});
test('App explicitly avoids unsafe alcohol and step incentives',()=>{for(const needle of ['No week automatically unlocks','Food, water, normal BP and feeling fine','A log, not a target','not a medical device','not manufacturer-tested'])assert.ok(source.includes(needle),needle);});
test('Production HTML has no inline script, external tracking or account-specific health data',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/<script type="module" src="\/app\.js"><\/script>/);assert.ok(!/<script(?![^>]*src=)/i.test(html));assert.ok(!/Gerard Wylie|gerardwylie91|GoogleAnalytics|gtag\(|facebook\.net/.test(html));});
test('Security headers prohibit third-party scripts and framing',()=>{const c=JSON.parse(fs.readFileSync(path.join(here,'generated-vercel.json'),'utf8'));const headers=c.headers[0].headers;const csp=headers.find(h=>h.key==='Content-Security-Policy').value;assert.ok(csp.includes("script-src 'self'"));assert.ok(csp.includes("frame-ancestors 'none'"));assert.ok(!csp.includes("script-src 'self' 'unsafe-inline'"));assert.equal(c.outputDirectory,'public');});
test('Install manifest supplies genuine 192px and 512px PNG icons',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(root,'public/manifest.webmanifest'),'utf8'));assert.equal(manifest.display,'standalone');for(const n of [192,512]){const p=fs.readFileSync(path.join(root,'public/icon-'+n+'.png'));assert.equal(p.readUInt32BE(16),n);assert.equal(p.readUInt32BE(20),n);}});
test('AES-GCM backup round trip preserves a validated journal without plaintext metadata',async()=>{const s=app.initialState();s.profile.name='Synthetic privacy test A709';const salt=crypto.getRandomValues(new Uint8Array(16));const key=await app.deriveKey('unique synthetic passphrase A709',salt);assert.equal(key.extractable,false);const e=await app.seal(s,key,salt);assert.ok(!JSON.stringify(e).includes(s.profile.name));assert.ok(!JSON.stringify(e).includes('unique synthetic passphrase'));const restored=await app.unseal(e,'unique synthetic passphrase A709');assert.equal(restored.state.profile.name,s.profile.name);assert.equal(e.iterations,600000);});
test('Wrong passphrases and ciphertext tampering fail authentication',async()=>{const s=app.initialState(),salt=crypto.getRandomValues(new Uint8Array(16)),key=await app.deriveKey('another synthetic passphrase 778',salt),e=await app.seal(s,key,salt);await assert.rejects(app.unseal(e,'incorrect synthetic passphrase'));const bad=clone(e);const bytes=Buffer.from(bad.data,'base64');bytes[0]^=1;bad.data=bytes.toString('base64');await assert.rejects(app.unseal(bad,'another synthetic passphrase 778'));});
test('Every encrypted save gets a fresh nonce and revision',async()=>{const salt=crypto.getRandomValues(new Uint8Array(16)),key=await app.deriveKey('fresh nonce synthetic test passphrase',salt),s=app.initialState(),a=await app.seal(s,key,salt),b=await app.seal(s,key,salt);assert.notEqual(a.iv,b.iv);assert.notEqual(a.data,b.data);assert.notEqual(a.revision,b.revision);});
test('Unsupported encryption metadata is rejected before accepting a backup',async()=>{await assert.rejects(app.unseal({format:'steady-encrypted-v1',kdf:'PBKDF2-SHA256',iterations:1,salt:'x',iv:'x',data:'x'},'any phrase'));});
